services:
  frontend:
    build:
      context: ./
      dockerfile: prod.Dockerfile
      target: prod
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL}
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://frontend:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 5