services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      target: prod
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      args:
        BUILD_ENV: prod
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_PORT=6432
      - DB_DATABASE=${DATABASE_NAME}
      - DB_USERNAME=${DATABASE_USERNAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  database:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
      - POSTGRESQL_PORT_NUMBER=6432